### ISSUE TITLE
Customise EMIKAT Tables

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/simple-table-component#10]
Hide columns not relevant for the user, e.g. grid cell. See also https://github.com/clarity-h2020/emikat/issues/23

**Comment by humerh** [comment]
The structure of the REST call is as shown below:

|             url           |     meaning       |
| ------------------ | -----------------|
| https://service.emikat.at/EmiKatTst/api/scenarios/1234 | 1234 for emikatId |
|      /feature/tab.name  |  tab.name  for name of emikat-Table |
|      /table/data  |  table/data for type of the output    (table/csv,  table/geotiff) |
|      ?fromow=0&rownum=1000   |  paging of result |
|       &column=aaa&column=bbb&column=ccc |  name of columns, which should be displayed (if omitted: ALL). Here: aaa, bbb and ccc |
 |      &sortby=aaa&sortby=bbb DESC  |  sorting of result; "bbb DESC" means column bbb is sorted  descending |

**Comment by p-a-s-c-a-l** [comment]
done
