### ISSUE TITLE
Combined Heat and Flood Tables

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/simple-table-component#18]
Based on [Combined Heat and Flood Views](https://github.com/clarity-h2020/emikat/issues/46), the tables for exposure, hc-le and impact have to be updated.

**Comment by humerh** [comment]
Should we add a PREFIX to the columns for the combined table to indicate to which hazard type a column belongs to?

Example: DISCOMFORT_LEVEL  -> HW_DISCOMFORT_LEVEL  ??

**Comment by p-a-s-c-a-l** [comment]
Yes, IMHO that would make sense. @DenoBeno any opinion on that?

**Comment by p-a-s-c-a-l** [comment]
Those are the column names for Heat and Flood Hazard with Local Effects ([view.3154](https://service.emikat.at/EmiKatTst/api/scenarios/3183/feature/view.3154/table/data?rownum=1000&filter=SZ_ID=3183&filter=TIME_PERIOD%3D%27Baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27Rare%27))

id | columnnames
-- | --
0 | "GRID_ID"
1 | "MULTIPOLYGON"
2 | "STUDY_VARIANT"
3 | "TIME_PERIOD"
4 | "EMISSIONS_SCENARIO"
5 | "EVENT_FREQUENCY"
6 | "HW_T_MRT"
7 | "HW_T_UTCI"
8 | "HW_T_A"
9 | "HW_DISCOMFORT_LEVEL"
10 | "PF_STREAMS"
11 | "PF_CL_STREAMS"
12 | "PF_DELTA_ELEV"
13 | "PF_CL_DELTA_ELEV"
14 | "PF_RUN_OFF_AVERAGE"
15 | "PF_CL_RUNOFF"
16 | "PF_RAIN_MM"
17 | "PF_CL_RAIN"
18 | "PF_PROP"
19 | "SZM_SZENARIO_REF"

**Comment by p-a-s-c-a-l** [comment]
Those are the column names for Heat and Flood Impact ([view.31559](https://service.emikat.at/EmiKatTst/api/scenarios/3183/feature/view.3155/table/data?rownum=1000&filter=SZ_ID=3183&filter=TIME_PERIOD%3D%27Baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27Rare%27))

id | columnnames
-- | --
0 | "GRID_ID"
1 | "MULTIPOLYGON"
2 | "STUDY_VARIANT"
3 | "TIME_PERIOD"
4 | "EMISSIONS_SCENARIO"
5 | "EVENT_FREQUENCY"
6 | "HW_EXPOSEDQUANTITY"
7 | "HW_DAMAGEPROBABILITY"
8 | "HW_DAMAGEQUANTITY"
9 | "HW_DISCOMFORT_LEVEL"
10 | "HW_POPULATION_DENSITY_CLASS"
11 | "HW_HEAT_WAVE_IMPACT"
12 | "AO_COST_DEVELOPMENT"
13 | "AO_COST_MAINTENANCE"
14 | "AO_COST_RETROFITTING"
15 | "PF_RESIDENTIAL_BUILDINGS"
16 | "PF_NON_RESIDENTIAL_BUILDINGS"
17 | "PF_ROADS_M2"
18 | "PF_DAMAGEPROBABILITY"
19 | "PF_DAMAGE_CLASS"
20 | "PF_FLOOD_IMPACT_EURO"
21 | "SZM_SZENARIO_REF"

**Comment by p-a-s-c-a-l** [comment]
Unless any other table view, `'tab.CLY_HAZARD_EVENTS_STUDY.2036'` does not like parameter SZ_ID:

``
{
  "type": "error",
  "message": "Error during data retrieval - EMIKAT-Server.DB_ERROR: Can't access db: java.sql.SQLSyntaxErrorException: ORA-00904: \"SZ_ID\": ungültiger Bezeichner\n - . Last cmd: \"SELECT /*+ FIRST_ROWS */ h0.OBJECT_ID c1, h0.LATITUDE c2, h0.LONGITUDE c3, h0.URBAN_AREA c4, h0.COUNTRY c5, h0.HAZARD_EVENT_TYPE_ID c6, h0.HAZARD_EVENT_TYPE_ID c7, h6749.ACRONYM c8, h0.RCP c9, h6732.ACRONYM c10, h0.PERIOD c11, h6733.ACRONYM c12, h0.FREQUENCY c13, h0.EVENT_DESCRIPTOR c14, h0.TX95P c15  FROM EMIKATSYS.CLY_HAZARD_EVENTS_STUDY h0, EMIKATSYS.CLY_EMISSIONS_SCENARIO h6732, EMIKATSYS.CLY_HAZARD_EVENT_TYPE h6749, EMIKATSYS.CLY_TIME_PERIOD h6733 WHERE (h0.SZM_SZENARIO_REF=3209) AND (h6749.SZM_VERSION_REF(+) = /* Long */8331) AND h0.RCP = h6732.EMISSIONSSCENARIO_ID (+) AND (h0.HAZARD_EVENT_TYPE_ID = h6749.HAZARD_EVENT_TYPE_ID (+)) AND (h0.PERIOD = h6733.TIMEPERIOD_ID (+)) AND (SZ_ID=3209) AND (h6733.ACRONYM='Baseline') AND (h6732.ACRONYM='Baseline') AND (h0.FREQUENCY='Frequent')\""
}
``

**Comment by p-a-s-c-a-l** [comment]
[RiskAndImpactTable](https://csis-dev.myclimateservice.eu/apps/simple-table-component/build/RiskAndImpactTable/?host=https://csis-dev.myclimateservice.eu&study_uuid=3d8327f4-c47f-4c9e-bbc3-fb9018ea9607&study_area=POLYGON((23.555632%2046.059224,23.555632%2046.085305,23.60095%2046.085305,23.60095%2046.059224,23.555632%2046.059224))&emikat_id=3209&datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&time_period=Baseline&emissions_scenario=Baseline&event_frequency=Frequent) for reference Study "[Advanced Screening Alba Iulia](https://csis-dev.myclimateservice.eu/study/33)" (CSIS ID: 33, EMIKAT ID: 3209):

![image](https://user-images.githubusercontent.com/1788226/88921697-3fb12c00-d26f-11ea-9fc4-e6d796074151.png)

**Comment by p-a-s-c-a-l** [comment]
[AdaptationOptionsAppraisalTable](https://csis-dev.myclimateservice.eu/apps/simple-table-component/build/AdaptationOptionsAppraisalTable/?host=https://csis-dev.myclimateservice.eu&study_uuid=3d8327f4-c47f-4c9e-bbc3-fb9018ea9607&study_area=POLYGON((23.555632%2046.059224,23.555632%2046.085305,23.60095%2046.085305,23.60095%2046.059224,23.555632%2046.059224))&emikat_id=3209&datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&time_period=Baseline&emissions_scenario=Baseline&event_frequency=Frequent) for reference Study "[Advanced Screening Alba Iulia](https://csis-dev.myclimateservice.eu/study/33)" (CSIS ID: 33, EMIKAT ID: 3209):

![image](https://user-images.githubusercontent.com/1788226/88926864-ddf4c000-d276-11ea-903f-374bee50de0e.png)

**Comment by p-a-s-c-a-l** [comment]
[CharacteriseHazardTable](https://csis-dev.myclimateservice.eu/apps/simple-table-component/build/CharacteriseHazardTable/?host=https://csis-dev.myclimateservice.eu&study_uuid=3d8327f4-c47f-4c9e-bbc3-fb9018ea9607&study_area=POLYGON((23.555632%2046.059224,23.555632%2046.085305,23.60095%2046.085305,23.60095%2046.059224,23.555632%2046.059224))&emikat_id=3209&datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&time_period=Baseline&emissions_scenario=Baseline&event_frequency=Frequent) for reference Study "[Advanced Screening Alba Iulia](https://csis-dev.myclimateservice.eu/study/33)" (CSIS ID: 33, EMIKAT ID: 3209):

![image](https://user-images.githubusercontent.com/1788226/88927322-89057980-d277-11ea-82ac-e9578ffbf200.png)

**Comment by p-a-s-c-a-l** [comment]
[ExposureTable](https://csis-dev.myclimateservice.eu/apps/simple-table-component/build/ExposureTable/?host=https://csis-dev.myclimateservice.eu&study_uuid=3d8327f4-c47f-4c9e-bbc3-fb9018ea9607&study_area=POLYGON((23.555632%2046.059224,23.555632%2046.085305,23.60095%2046.085305,23.60095%2046.059224,23.555632%2046.059224))&emikat_id=3209&datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&time_period=Baseline&emissions_scenario=Baseline&event_frequency=Frequent) for reference Study "[Advanced Screening Alba Iulia](https://csis-dev.myclimateservice.eu/study/33)" (CSIS ID: 33, EMIKAT ID: 3209):

![image](https://user-images.githubusercontent.com/1788226/88927778-3aa4aa80-d278-11ea-8238-f035eb02397d.png)

**Comment by p-a-s-c-a-l** [comment]
[CharacteriseHazardTable](https://csis-dev.myclimateservice.eu/apps/simple-table-component/build/HazardLocalEffectsTable/?host=https://csis-dev.myclimateservice.eu&study_uuid=3d8327f4-c47f-4c9e-bbc3-fb9018ea9607&study_area=POLYGON((23.555632%2046.059224,23.555632%2046.085305,23.60095%2046.085305,23.60095%2046.059224,23.555632%2046.059224))&emikat_id=3209&datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&time_period=Baseline&emissions_scenario=Baseline&event_frequency=Frequent) for reference Study "[Advanced Screening Alba Iulia](https://csis-dev.myclimateservice.eu/study/33)" (CSIS ID: 33, EMIKAT ID: 3209):

![image](https://user-images.githubusercontent.com/1788226/88927879-61fb7780-d278-11ea-8c99-d6452cfffbee.png)

**Comment by p-a-s-c-a-l** [comment]
done
