### ISSUE TITLE
Data Download

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/simple-table-component#7]
Support download of data in ~different formats~ in CSV format supported by the EMIKAT APIs.

**Comment by p-a-s-c-a-l** [comment]
See https://github.com/tannerlinsley/react-table/wiki/FAQ#how-do-i-get-at-the-internal-data-so-i-can-do-things-like-exporting-to-a-file

**Comment by DenoBeno** [comment]
that would be helpful indeed

**Comment by p-a-s-c-a-l** [comment]
May be obsoleted by https://github.com/clarity-h2020/csis/issues/110

**Comment by p-a-s-c-a-l** [comment]
Done.
